---
- name: install php xdebug
  apt:
    pkg: php{{ xdebug_php_version }}-xdebug
    state: present

- name: configure xdebug
  template:
    src: xdebug.ini.j2
    dest: /etc/php/{{ php_version }}/mods-available/xdebug.ini
